export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const AUTH_REMOVE_TOKEN = 'AUTH_REMOVE_TOKEN';

export const MAIN_SET_THUMBS = 'MAIN_SET_THUMBS';
export const MAIN_REMOVE_THUMBS = 'MAIN_REMOVE_THUMBS';

export const UI_START_LOADING_GENERATE = 'UI_START_LOADING_GENERATE';
export const UI_STOP_LOADING_GENERATE = 'UI_STOP_LOADING_GENERATE';